import type { Metadata } from "next";
import LegalPage from "@/components/legal/LegalPage";

export const metadata: Metadata = {
  title: "Terms of Service — Meridian Legal Intelligence",
};

function H2({ children }: { children: React.ReactNode }) {
  return <h2 className="font-serif-brand text-xl font-semibold text-navy">{children}</h2>;
}

export default function TermsPage() {
  return (
    <LegalPage title="Terms of Service" effectiveDate="October 5, 2026">
      <section>
        <H2>1. Agreement to Terms</H2>
        <p className="mt-3">
          These Terms of Service (&quot;Terms&quot;) govern your access to and use of the Meridian
          Legal Intelligence platform, including our website, client portal, and related services
          (collectively, the &quot;Service&quot;), operated by Meridian Legal Intelligence
          (&quot;Meridian,&quot; &quot;we,&quot; &quot;us,&quot; or &quot;our&quot;). By creating a
          workspace, logging in, or otherwise using the Service, you agree to be bound by these
          Terms. If you are using the Service on behalf of an organization, you represent that you
          have authority to bind that organization, and &quot;you&quot; refers to that organization.
        </p>
      </section>

      <section>
        <H2>2. The Service Is Not Legal Advice</H2>
        <p className="mt-3">
          Meridian is a software platform that retrieves, summarizes, and drafts text based on
          documents you provide and on public legal source materials. <strong>Meridian does not
          practice law, is not a law firm, and does not provide legal advice.</strong> Nothing
          generated by the Service — including answers, citations, summaries, or drafted clause
          language — constitutes legal advice or creates an attorney-client relationship between
          you and Meridian.
        </p>
        <p className="mt-3">
          All output must be independently reviewed by a licensed attorney qualified in the
          relevant jurisdiction before you rely on it, file it, send it, or otherwise act on it.
          You are solely responsible for how you use the Service&apos;s output. See our{" "}
          <a href="/disclaimer" className="font-medium text-navy underline">
            AI Output Disclaimer
          </a>{" "}
          for further detail.
        </p>
      </section>

      <section>
        <H2>3. Eligibility and Accounts</H2>
        <p className="mt-3">
          You must be at least 18 years old and capable of forming a binding contract to use the
          Service. The current authentication method is a lightweight, email-based login intended
          for demonstration and internal use; you are responsible for safeguarding access to any
          workspace created under your organization and for all activity that occurs under it. You
          agree to provide accurate information when creating a workspace and to notify us promptly
          of any unauthorized access.
        </p>
      </section>

      <section>
        <H2>4. Your Content</H2>
        <p className="mt-3">
          &quot;Your Content&quot; means the documents, queries, and other materials you upload or
          submit to the Service. As between you and Meridian, you retain all ownership rights in
          Your Content. You grant Meridian a limited license to host, process, index, and transmit
          Your Content solely to provide the Service to you, including to retrieval and generation
          providers as described in our{" "}
          <a href="/privacy" className="font-medium text-navy underline">
            Privacy Policy
          </a>
          .
        </p>
        <p className="mt-3">
          You represent that you have all rights necessary to upload Your Content and that doing so
          does not violate any third party&apos;s rights, confidentiality obligations (including
          attorney-client privilege or protective orders), or applicable law. You are solely
          responsible for Your Content and for ensuring you have appropriate authorization — including
          client consent where required — before uploading client or matter materials.
        </p>
      </section>

      <section>
        <H2>5. Workspace Isolation</H2>
        <p className="mt-3">
          The Service is designed so that each workspace&apos;s private documents are retrieved and
          returned only within that workspace, with isolation enforced at the data-retrieval layer.
          While we design and test for this, the Service is provided on an &quot;as is&quot; basis
          as described in Section 8, and we do not guarantee the complete absence of defects. If you
          believe isolation between workspaces has failed, notify us immediately at{" "}
          <a href="mailto:security@meridianlegal.ai" className="font-medium text-navy underline">
            security@meridianlegal.ai
          </a>
          .
        </p>
      </section>

      <section>
        <H2>6. Acceptable Use</H2>
        <p className="mt-3">You agree not to:</p>
        <ul className="mt-3 list-disc space-y-2 pl-6">
          <li>Use the Service to violate any applicable law or regulation;</li>
          <li>Upload content you do not have the right to upload, or that infringes a third party&apos;s rights;</li>
          <li>Attempt to access another workspace&apos;s documents or credentials, or probe, scan, or test the Service&apos;s security;</li>
          <li>Use the Service to generate content intended to deceive a court, counterparty, or regulator as to its source or authorship;</li>
          <li>Reverse-engineer, resell, or use the Service to build a competing product; or</li>
          <li>Interfere with or disrupt the integrity or performance of the Service.</li>
        </ul>
      </section>

      <section>
        <H2>7. Third-Party AI Providers</H2>
        <p className="mt-3">
          Generating answers and drafts may involve sending portions of Your Content to a
          third-party large language model provider (for example, Anthropic), or to a model running
          locally within your own infrastructure, depending on your configuration. See our{" "}
          <a href="/privacy" className="font-medium text-navy underline">
            Privacy Policy
          </a>{" "}
          for details on which providers may process Your Content and how.
        </p>
      </section>

      <section>
        <H2>8. Disclaimers</H2>
        <p className="mt-3">
          THE SERVICE AND ALL OUTPUT ARE PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE,&quot;
          WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED, OR STATUTORY, INCLUDING WITHOUT
          LIMITATION WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,
          NON-INFRINGEMENT, OR ACCURACY. WE DO NOT WARRANT THAT ANSWERS OR DRAFTED TEXT ARE
          COMPLETE, CORRECT, OR SUITABLE FOR ANY PARTICULAR MATTER, OR THAT THE SERVICE WILL BE
          UNINTERRUPTED OR ERROR-FREE.
        </p>
      </section>

      <section>
        <H2>9. Limitation of Liability</H2>
        <p className="mt-3">
          TO THE MAXIMUM EXTENT PERMITTED BY LAW, MERIDIAN AND ITS OFFICERS, EMPLOYEES, AND
          SUPPLIERS WILL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR
          PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS, DATA, GOODWILL, OR OTHER INTANGIBLE LOSSES,
          ARISING OUT OF OR RELATED TO YOUR USE OF THE SERVICE, INCLUDING RELIANCE ON ANY OUTPUT.
          OUR TOTAL LIABILITY FOR ANY CLAIM ARISING OUT OF THESE TERMS OR THE SERVICE WILL NOT
          EXCEED THE GREATER OF (A) THE AMOUNT YOU PAID US IN THE TWELVE MONTHS BEFORE THE CLAIM
          AROSE, OR (B) ONE HUNDRED U.S. DOLLARS ($100). Some jurisdictions do not allow certain
          limitations of liability, so some of the above limitations may not apply to you.
        </p>
      </section>

      <section>
        <H2>10. Indemnification</H2>
        <p className="mt-3">
          You agree to indemnify and hold Meridian harmless from any claims, damages, liabilities,
          and expenses (including reasonable attorneys&apos; fees) arising out of Your Content, your
          use of the Service in violation of these Terms, or your violation of any law or
          third-party right.
        </p>
      </section>

      <section>
        <H2>11. Termination</H2>
        <p className="mt-3">
          You may stop using the Service at any time. We may suspend or terminate your access if we
          reasonably believe you have violated these Terms, or for any reason upon notice. Sections
          2, 4, 8, 9, 10, and 13 survive termination.
        </p>
      </section>

      <section>
        <H2>12. Changes to the Service or These Terms</H2>
        <p className="mt-3">
          We may modify the Service or these Terms from time to time. We will post the updated
          Terms with a new effective date. Continued use of the Service after changes take effect
          constitutes acceptance of the revised Terms.
        </p>
      </section>

      <section>
        <H2>13. Governing Law and Disputes</H2>
        <p className="mt-3">
          <em>
            [Placeholder — to be completed with counsel: these Terms are governed by the laws of
            [State/Country], without regard to conflict-of-laws principles. The parties agree to
            resolve disputes exclusively in the courts located in [Venue], or, if elected, through
            binding arbitration under [Arbitration Body/Rules].]
          </em>
        </p>
      </section>

      <section>
        <H2>14. Contact</H2>
        <p className="mt-3">
          Questions about these Terms can be sent to{" "}
          <a href="mailto:legal@meridianlegal.ai" className="font-medium text-navy underline">
            legal@meridianlegal.ai
          </a>
          .
        </p>
      </section>
    </LegalPage>
  );
}
